# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: router-daemon/proto/router.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'router-daemon/proto/router.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n router-daemon/proto/router.proto\x12\x06router\"\x8e\x01\n\rRouterRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08modality\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x17\n\x0f\x65motion_valence\x18\x04 \x01(\x02\x12\x17\n\x0f\x65motion_arousal\x18\x05 \x01(\x02\x12\x17\n\x0f\x65motion_primary\x18\x06 \x01(\t\"\x9a\x01\n\x0eRouterDecision\x12\x12\n\nexpert_ids\x18\x01 \x03(\t\x12\x1a\n\x12\x63heck_memory_first\x18\x02 \x01(\x08\x12\x17\n\x0finternet_needed\x18\x03 \x01(\x08\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x17\n\x0freasoning_trace\x18\x05 \x01(\t\x12\x12\n\nlatency_ms\x18\x06 \x01(\x02\"2\n\nMapRequest\x12\x11\n\texpert_id\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\"3\n\x0bMapResponse\x12\x0e\n\x06mapped\x18\x01 \x01(\x08\x12\x14\n\x0cmapped_count\x18\x02 \x01(\r\"!\n\x0c\x45victRequest\x12\x11\n\texpert_id\x18\x01 \x01(\t\"6\n\rEvictResponse\x12\x0f\n\x07\x65victed\x18\x01 \x01(\x08\x12\x14\n\x0cmapped_count\x18\x02 \x01(\r2H\n\rRouterService\x12\x37\n\x06\x44\x65\x63ide\x12\x15.router.RouterRequest\x1a\x16.router.RouterDecision2\x81\x01\n\rExpertService\x12\x34\n\tMapExpert\x12\x12.router.MapRequest\x1a\x13.router.MapResponse\x12:\n\x0b\x45victExpert\x12\x14.router.EvictRequest\x1a\x15.router.EvictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'router_daemon.proto.router_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTERREQUEST']._serialized_start=45
  _globals['_ROUTERREQUEST']._serialized_end=187
  _globals['_ROUTERDECISION']._serialized_start=190
  _globals['_ROUTERDECISION']._serialized_end=344
  _globals['_MAPREQUEST']._serialized_start=346
  _globals['_MAPREQUEST']._serialized_end=396
  _globals['_MAPRESPONSE']._serialized_start=398
  _globals['_MAPRESPONSE']._serialized_end=449
  _globals['_EVICTREQUEST']._serialized_start=451
  _globals['_EVICTREQUEST']._serialized_end=484
  _globals['_EVICTRESPONSE']._serialized_start=486
  _globals['_EVICTRESPONSE']._serialized_end=540
  _globals['_ROUTERSERVICE']._serialized_start=542
  _globals['_ROUTERSERVICE']._serialized_end=614
  _globals['_EXPERTSERVICE']._serialized_start=617
  _globals['_EXPERTSERVICE']._serialized_end=746
# @@protoc_insertion_point(module_scope)
